package com.iforum.demo.entity;

public class message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.time
     *
     * @mbg.generated
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.belongto
     *
     * @mbg.generated
     */
    private Integer belongto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.context
     *
     * @mbg.generated
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.time
     *
     * @return the value of message.time
     *
     * @mbg.generated
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.time
     *
     * @param time the value for message.time
     *
     * @mbg.generated
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.belongto
     *
     * @return the value of message.belongto
     *
     * @mbg.generated
     */
    public Integer getBelongto() {
        return belongto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.belongto
     *
     * @param belongto the value for message.belongto
     *
     * @mbg.generated
     */
    public void setBelongto(Integer belongto) {
        this.belongto = belongto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.context
     *
     * @return the value of message.context
     *
     * @mbg.generated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.context
     *
     * @param context the value for message.context
     *
     * @mbg.generated
     */
    public void setContext(String context) {
        this.context = context == null ? null : context.trim();
    }
}