package com.iforum.demo.entity;

public class smallforum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smallforum.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smallforum.smallforumname
     *
     * @mbg.generated
     */
    private String smallforumname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smallforum.smallchairmanid
     *
     * @mbg.generated
     */
    private String smallchairmanid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smallforum.belongto
     *
     * @mbg.generated
     */
    private Integer belongto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smallforum.id
     *
     * @return the value of smallforum.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smallforum.id
     *
     * @param id the value for smallforum.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smallforum.smallforumname
     *
     * @return the value of smallforum.smallforumname
     *
     * @mbg.generated
     */
    public String getSmallforumname() {
        return smallforumname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smallforum.smallforumname
     *
     * @param smallforumname the value for smallforum.smallforumname
     *
     * @mbg.generated
     */
    public void setSmallforumname(String smallforumname) {
        this.smallforumname = smallforumname == null ? null : smallforumname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smallforum.smallchairmanid
     *
     * @return the value of smallforum.smallchairmanid
     *
     * @mbg.generated
     */
    public String getSmallchairmanid() {
        return smallchairmanid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smallforum.smallchairmanid
     *
     * @param smallchairmanid the value for smallforum.smallchairmanid
     *
     * @mbg.generated
     */
    public void setSmallchairmanid(String smallchairmanid) {
        this.smallchairmanid = smallchairmanid == null ? null : smallchairmanid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smallforum.belongto
     *
     * @return the value of smallforum.belongto
     *
     * @mbg.generated
     */
    public Integer getBelongto() {
        return belongto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smallforum.belongto
     *
     * @param belongto the value for smallforum.belongto
     *
     * @mbg.generated
     */
    public void setBelongto(Integer belongto) {
        this.belongto = belongto;
    }
}