package com.iforum.demo.mapper;

import com.iforum.demo.entity.user;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insertSelective(user record);

    user getUserByAccountNum(String accountNum);

    int updateUser(String accoutNum);

    int deleteUserByAccountNum(String accoutNum);

    List<user> getAllUser();
}